### ISSUE TITLE
Collect requirements for new monitoring

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/monitoring#2]
https://github.com/wmo-im/monitoring/wiki/requirements
@wmo-im/tt-wis-monitoring

**Comment by EgawaTakumu** [comment]
I was working in the NWP division and in charge of satellite radiance assimilation several years ago. So I would like to comment from that perspective.
It might be difficult to count the raw number of satellite observation data. This is because the number is very large and the data format and repetition (path, scan, channnel) depends on the instrument. The data used in the NWP is thinned considerably. Simply counting the number of files would be meaningless. Because polar orbit satellites have global data and directly received data.
Cut-off time depends on the NWP centres and their models. The JMA runs the high resolution regional model every hour and should be trying to get the satellite observation data every 30 minutes (probably). We also need to read the data to check the cut-off time accurately, which can be difficult.
I think it's important to check the data format, but it's sometimes difficult to follow the new BUFR master table version. We are using JAVA library but it seems to have some bugs....
For your reference, I will tell you the URL of the monitoring page operated by the NWP division of JMA:
	http://qc.kishou.go.jp/
As for conventional data, monitoring report seems to be legacy one. (Sorry, I don't know the details.) As for satellite data, you can check time series of statistics with images.

**Comment by kaiwirt** [comment]
Closed: This is basically the ToR
