### ISSUE TITLE
Agree on a common URL to provide metrics for the global monitoring

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/monitoring#34]
In order to scrape the metrics of centers, the Global Monitoring Center needs to know the URL of the metric endpoint. We need to decide whether we want to 

- Fix the URL, such that apart from the domain part, the monitoring metrics are exposed under a common URL
- Make the monitoring URL a part of the registration process, such that the Global Monitoring Centers can maintain a list of endpoints
- Provide the URL via Metadata through the GDC

**Comment by guwj0609** [comment]
@kaiwirt

**Comment by kaiwirt** [comment]
Any thoughts on this @golfvert 

I think Option 2 might be the easiest solution.

**Comment by golfvert** [comment]
Who are the sources of the metrics ? I guess here we are not talking about "specialized" metrics. Just stuff to check that things are working as expected. Right ?
If that is the case, and in order to simplify the architecture, I think that the sources will NOT be the WIS2 Nodes but only the various Global Services ? In this case, option 2 is easy...

**Comment by kaiwirt** [comment]
Yes. Its about global services and possibly sensor centers. The GM somehow needs to know where to find the metrics.

**Comment by kaiwirt** [comment]
Closed as this is part of the registration process
